# Generated by Django 5.2.8 on 2026-01-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_lecture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
