# Generated by Django 6.0.1 on 2026-01-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_course_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(default='images/tricia.jpeg', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(blank=True, default='images/tricia.jpeg', null=True, upload_to='images/'),
        ),
    ]
