# Generated by Django 6.0.1 on 2026-01-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_program_image_alter_lecture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.PositiveIntegerField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default=100, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='4', max_length=2),
            preserve_default=False,
        ),
    ]
