# Generated by Django 6.0.1 on 2026-02-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_course_amount_course_description_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
