# Generated by Django 6.0.1 on 2026-02-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_testchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='testchoice',
            name='name',
            field=models.CharField(default='stephen', verbose_name=20),
            preserve_default=False,
        ),
    ]
