# Generated by Django 6.0.1 on 2026-02-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0009_testchoice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testchoice',
            name='choice',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('Graduate', 'graduated'), ('drop out', 'dropped out')], default='null', max_length=50),
            preserve_default=False,
        ),
    ]
